### ISSUE TITLE
Step by step for Clj noobs?

### ISSUE THREAD

**Issue by Brick-Tamland** [tshort/dactyl-keyboard#13]
Clojure noob here. Got lost somewhere along the way, wondering if someone could point me in the right direction?
 
Get Clojure runtime. check.
Get Leiningen. Check
Get OpenSCAD. Check.
Cloned adereth/dactyl-keyboard repo. Check. 
Open things/*Scad file in OpenSCAD. Cool. 

Now here is where I am lost:
Have Dactyl.clj open in Sublime3
Changed rows to 6x6
Saved.
in Terminal Cd to src/dactyl-keyboard/dactyl.clj
Lein repl. 
load-file "src/dactyl-keyboard/dactyl.clj"
Get this ouput:
#object[clojure.lang.RT$3 0x6106f905 "clojure.lang.RT$3@6106f905"]
"src/dactyl_keyboard/dactyl.clj"

And no changes to things/*scad files or to OpenSCAD render?

**Comment by l4u** [comment]
Edit `src/dactyl_keyboard/dactyl.clj` with
```
(def nrows 6)
(def ncols 6)
```

run `lein repl`. I did this in the root of the project.
In the REPL, run `(load-file "src/dactyl_keyboard/dactyl.clj")`. Note that the parentheses are required.

The output should be `#'dactyl-keyboard.dactyl/-main`

Open `things/left.scad`, and you should be able to see the new files.

**Comment by Brick-Tamland** [comment]
Great googly moogly. {hand slaps forehead} @l4u Thank you!

**Comment by l4u** [comment]
@Brick-Tamland I've just made a PR for improving this process.
see https://github.com/tshort/dactyl-keyboard/pull/15
