### ISSUE TITLE
Extra inner wall

### ISSUE THREAD

**Issue by fi0** [tshort/dactyl-keyboard#16]
https://imgur.com/a/tcvJX

Although it doesn't affect the keyboard usage, the extra inner wall should be removed.
Which lines should I look into?

**Comment by tshort** [comment]
That corner is pretty tricky. The programming there is pretty klunky and mostly trial and error. Here's a starting point:

https://github.com/tshort/dactyl-keyboard/blob/7b26338842899833d0da75a9b0e75466d0553af5/src/dactyl_keyboard/dactyl.clj#L553

**Comment by tshort** [comment]
I realize you might be talking about another corner. I'll have to check later.
