### ISSUE TITLE
"object is not manifold" when importing into repetier

### ISSUE THREAD

**Issue by edvorg** [tshort/dactyl-keyboard#22]
Hi. 3d models, 5x6 in particular, seem to not be manifold and can't be sliced by slic3r
 Is it known issue?

**Comment by jaredjennings** [comment]
@edvorg, I have the same problem with slic3r. Exporting from OpenSCAD using the AMF format gets me different, but still bad, results. I got MeshLab to try to clean up the model. When I imported the STL file, MeshLab asked me if I wanted to "unify duplicated vertices." If I tell it to do so, I get nonmanifold vertices and edges. If I tell it not to unify the vertices, everything works and I have no nonmanifold vertices nor edges.

I don't know how this helps either you or me, but it's something, I suppose.

**Comment by jaredjennings** [comment]
So on my other computer with slic3r 1.3.0 and OpenSCAD 2019.01-RC2, the STL loaded into Slic3r.

**Comment by jaredjennings** [comment]
After more experimentation it appears the OpenSCAD version matters more than that of Slic3r.

**Comment by jaredjennings** [comment]
ARGH forget everything I said. Besides the problems you mentioned, I've also run into adereth#60 except bigger (like several millimeters of layers missing), and now my other computer is making STLs just as bad as this one. I have not found out anything helpful after all so far.

**Comment by jaredjennings** [comment]
I finally printed successfully using Cura. Over in #2 some folks were saying they fixed the STL with Netfabb and were able to use it in Slic3r.

**Comment by edvorg** [comment]
Printed successfully using prusa slicer

**Comment by oleksandr** [comment]
@edvorg noticed a hole in PrusaSlicer - see image attached

<img width="560" alt="image" src="https://user-images.githubusercontent.com/183183/124325342-bbed7700-db84-11eb-8956-05611eb0b597.png">
