### ISSUE TITLE
Kailh-style housing compatibility

### ISSUE THREAD

**Issue by filoxo** [tshort/dactyl-keyboard#28]
Hi, thanks for this project! The design is awesome!

Would it be possible to remove the nubs on the sides of the switch cutouts? Those prevent us from using Kailh switch housings, which have grown in popularity. I'd suggest using a different model for the switch holes like recommended in https://github.com/tshort/dactyl-keyboard/issues/23
For the time being, I've used a small, low-velocity rotary tool to remove them which is just inconvenient.

**Comment by rishka** [comment]
#36 addresses this, I removed the nub, reduced the size of the hole and added cutouts for the switches to snap into
