### ISSUE TITLE
How to make 1.5u thumb keys 1u?

### ISSUE THREAD

**Issue by Ingvix** [tshort/dactyl-keyboard#43]
I've been making some changes for my own build without any previous experience with clojure.

I'd just like to ask how would I succesfully change the 1.5u thumb keys to 1u so that the case also realizes this? I've moved the top keys from thumb-15x-layout to thumb-1x-layout and removed the former altogether from the code. That alone clearly isn't enough and I'm in a point where I now got only the gaps left between the top thumb key holes and the case. I can't seem to figure out how would I go about closing the gaps, so help would be appreciated.

**Comment by ibnuda** [comment]
there are two easiest ways:

1. in `thumb-connectors`, change `thumb-post-xy` to `web-post-xy`. though it will only make the keys have 1u plates.
2. a bit harder, change the `translate [x y z]` part in `thumb-tr-place`  and `thumb-tl-place`, and then follow number 1.

hope it helps.

**Comment by Ingvix** [comment]
Thanks for the tips. Just changing `thumb-post-xy` within `thumb-connectors` wasn't quite enough as it was left some gaps in the case so I just ended up replacing it everywhere and now it works as I want it.

I'll be closing this as I'm satisfied with this but if someone knows even some better way, I'd be interested to know.
