### ISSUE TITLE
Weak micro-USB connector on the Arduino Pro Micro

### ISSUE THREAD

**Issue by tshort** [tshort/dactyl-keyboard#6]
I had one break off. My keyboard is still usable. It's still plugged in on the right side. I'm okay as long as I don't want to reprogram my left side:). 

This is a known problem with these cheap knock-off controllers.

I should redesign this to use a separate full-size USB connection and wire that to the Arduino Pro Micro.

**Comment by tshort** [comment]
Fixed in the latest design. It uses a full-size USB connection.

**Comment by guestisp** [comment]
Do you use an extension cable between the promicro and the printed case ? If yes, which one ?
